name: transcriberapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e
  permission_handler: ^11.0.1
  path_provider: ^2.1.5
  record: ^6.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  http: ^1.5.0
  mime: ^2.0.0
  http_parser: ^4.1.2
  flutter_dotenv: ^6.0.0
  rename: ^3.1.0
  intl: ^0.20.1
  audioplayers: ^6.5.1
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"